collection of ossfuzz fixes

diff --git a/research-oss/medium-oss/init/5/build b/research-oss/medium-oss/init/5/build
--- a/research-oss/medium-oss/init/5/build
+++ b/research-oss/medium-oss/init/5/build
@@ -2,10 +2,10 @@
 if [ "$?" -gt 0 ]; then
     exit 1
 fi
-. /usr/local/sbin/e
 export LABEL=$1
 export PROJECT_NAME=xvid
 export SANITIZER=$1
+. /usr/local/sbin/e
 if [ -z "$SANITIZER" ]; then
     export SANITIZER='none'
     export LABEL='none'$LABEL
@@ -27,22 +27,32 @@ if [ ! -d "/src-orig" ]; then
     build-cleanup-oss
 fi
 build-srcfolders
-if [ "$3" == "skip" ]; then
+if [ "$4" == "skip" ]; then
+    chown -hR hacker:hacker /src-$LABEL /out
     rm -rf /tmp/build.lck
 else
     mv /src-$LABEL /src
 
-    cd $SRC/$PROJECT_NAME
+    cd /src
+    rm -rf xvidcore-install
+
     if [ "$4" = "understanding" ]; then
-        understanding $2 $3
+        understanding_oss $2 $3
     elif [ "$4" = "planning" ]; then
         planning $2 $3
     else
         if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
             oss_help
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        elif [ "$3" != "$PROJECT_NAME" ]; then
+            echo "[ERROR] Project $3 not available in this challenge"
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
             exit 1
         fi
-        fuzzlog
+        fuzzlog_oss $SRC/oss-fuzz-fuzzers/xvid/*
         compile
         drivers > /dev/null
     fi
diff --git a/research-oss/simple-oss/init/2/build b/research-oss/simple-oss/init/2/build
--- a/research-oss/simple-oss/init/2/build
+++ b/research-oss/simple-oss/init/2/build
@@ -2,10 +2,10 @@
 if [ "$?" -gt 0 ]; then
     exit 1
 fi
-. /usr/local/sbin/e
 export LABEL=$1
-export PROJECT_NAME=usbguard
+export PROJECT_NAME=vorbis
 export SANITIZER=$1
+. /usr/local/sbin/e
 if [ -z "$SANITIZER" ]; then
     export SANITIZER='none'
     export LABEL='none'$LABEL
@@ -13,51 +13,48 @@ fi
 
 if [ ! -d "/src-orig" ]; then
 #----------------------------------------------------------------------
-    #apt-get update && apt-get install -y make autoconf automake libtool pkg-config libxml2-utils1 libxml2-dev xsltproc \
-    #  libprotobuf-dev protobuf-compiler libdbus-1-dev libdbus-glib-1-dev libgio2.0-cil-dev libgcrypt20-dev \
-    #  libpolkit-gobject-1-dev libseccomp-dev libcap-ng-dev
-
-    #git clone https://github.com/ClusterLabs/libqb && cd libqb && \
-    #    ./autogen.sh && ./configure && make && make install
+    #apt-get update && apt-get install -y make autoconf automake ffmpeg libtool pkg-config python3 wget
+    #python3 -m pip install corpus-replicator
+    #git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
+    #git clone --depth 1 https://gitlab.xiph.org/xiph/vorbis.git
     cd $SRC
-    rm -rf $PROJECT_NAME
-    rm -rf inspector
+    cp -r /downloads/ogg $SRC
+    cp -r /downloads/vorbis $SRC
 
-    #git clone --recurse-submodules --depth 1 https://github.com/USBGuard/usbguard usbguard
-    cp -r /downloads/usbguard $SRC
-    cp -r /downloads/libqb $SRC
-    cd $SRC/libqb
-    ./autogen.sh
-    ./configure 
-    make 
-    make install 
+    corpus-replicator -o decode_corpus audio_vorbis_ogg_libvorbis.yml audio
+    # TODO: remove `people.xiph.org` lines once upstream build script is updated
+    mkdir people.xiph.org/
+    touch people.xiph.org/dummy.ogg
     cd /
-
-    # This is to fix Fuzz Introspector build by using LLVM old pass manager
-    # re https://github.com/ossf/fuzz-introspector/issues/305
-    export OLD_LLVMPASS=1
-
     cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
 #----------------------------------------------------------------------
     build-cleanup-oss
 fi
 build-srcfolders
-if [ "$3" == "skip" ]; then
+if [ "$4" == "skip" ]; then
+    chown -hR hacker:hacker /src-$LABEL /out
     rm -rf /tmp/build.lck
 else
     mv /src-$LABEL /src
 
     cd $SRC/$PROJECT_NAME
     if [ "$4" = "understanding" ]; then
-        understanding $2 $3
+        understanding_oss $2 $3
     elif [ "$4" = "planning" ]; then
         planning $2 $3
     else
         if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
             oss_help
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        elif [ "$3" != "$PROJECT_NAME" ]; then
+            echo "[ERROR] Project $3 not available in this challenge"
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
             exit 1
         fi
-        fuzzlog
+        fuzzlog_oss $SRC/$PROJECT_NAME/contrib/oss-fuzz/*.cc
         compile
         drivers > /dev/null
     fi
